/**
 * Packfile 兼容出口
 *
 * 具体实现已迁移到 `src/odb/pack/`，
 * 当前目录只保留原有导入路径的兼容层。
 */

export {
  OBJ_COMMIT,
  OBJ_TREE,
  OBJ_BLOB,
  OBJ_TAG,
  OBJ_OFS_DELTA,
  OBJ_REF_DELTA,
  PACK_SIGNATURE,
  PACK_VERSION,
  PACK_HEADER_SIZE,
  PACK_CHECKSUM_SIZE,
  IDX_V2_SIGNATURE,
  IDX_V2_VERSION,
  objectTypeToNumber,
  numberToObjectType,
  isDeltaType,
  decodeObjectHeader,
  encodeObjectHeader,
  decodeOfsDeltaOffset,
  encodeOfsDeltaOffset,
  decodeVarint,
  encodeVarint,
  applyDelta,
  createDelta,
  createPackReader,
  PackReader,
  type PackObject,
  createPackWriter,
  PackWriter,
  createPackIndexReader,
  createPackIndexWriter,
  PackIndexReader,
  PackIndexWriter,
  type PackIndexEntry,
  createPackObjectStore,
  PackObjectStore,
  type PackFileInfo,
  createCompositeObjectStore,
  CompositeObjectStore,
  createPackBuilder,
  PackBuilder,
  type PackBuildResult,
} from "../odb/pack/index.ts";
